---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    db_host: 10.132.0.44
  tasks:
    - name: Change mongo config file
      become: true #Root privileges
      template:
        src: template/mongod.conf.j2 #Local template
        dest: /etc/mongod.conf #Remote path
        mode: 0644 #File privileges
      tags: db-tag
      notify: restart mongod
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma
    - name: Add config for DB connection
      template:
        src: template/db_config.j2
        dest: /home/appuser/db_config
      tags: app-tag
    - name: Enable Puma service
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith #Correct branch in github
      tags: deploy-tag
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag
  handlers:
  - name: restart mongod
    become: true #Root privileges for handler
    service: name=mongod state=restarted #Task for handler
  - name: reload puma
    become: true #Root privileges for handler
    service: name=puma state=restarted #Task for handler